export const sidebarMenu: any[] = [
  {
    name: "Jobs",
    routerLink: ["/jobs"],
    identifier: "Jobs",
    iconClass: "icofont-briefcase",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
  },
  {
    name: "Candidates",
    routerLink: ["/candidates"],
    identifier: "Candidates",
    iconClass: "icofont-users-alt-2",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
  },
  {
    name: "Partners",
    routerLink: ["/partners"],
    identifier: "Partners",
    iconClass: "icofont-users-alt-2",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
  },
  {
    name: "Contact us Requests",
    routerLink: ["/contact_us"],
    identifier: "Contact us Requests",
    iconClass: "icofont-users-alt-2",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
  },
  {
    name: "Banners",
    routerLink: ["/banners"],
    identifier: "Banners",
    iconClass: "icofont-image",
    breadcrumbMessage: "",
    isCategory: false,
    isApp: false,
    children: [],
  }
];
