import { ROLE } from "enums/enums";
import { Notification } from "./Notification";
import { Project } from "./Project";

export interface User {
  id: string;
  code: string | null;
  company_info: { id: string; name: string };
  name: string | null;
  email: string | null;
  password: string | null;
  avatar: string | null;
  gender: string;
  address: string | null;
  residence_number: string | null;
  nationality: string | null;
  site_role: string | null;
  site_job: string | null;
  joining_date: string;
  iban_number: number;
  renewal_of_residence: string;
  id_number: string | null;
  id_ex_date: string | null;
  business_title: string | null;
  role: ROLE;
  is_loggedIn: boolean;
  kpi: number | null;
  working_hours: string | null;
  contract_date: string;
  contract_ex: string;
  salary_per_month: string | null;
  salary_per_hour: string | null;
  sign: string | null;
  shift_start: string | null;
  shift_end: string | null;
  file: string | null;
  is_verified: boolean;
  temp_otp: number | null;
  temp_password_code: string | null;
  // chats: Chat[];
  deletion_code: string | null;
  department_info: { id: string; name: string };
  projects_info: {
    id: string;
    name: string;
    longitude: number;
    latitude: number;
  }[];
  // department: Department;
  //attendances: Attendance[];
  notifications: Notification[];
  projects: Project[];
  manager_of: Project[];
  // groups: Group[];
  // kpi_records: UserKpi[];
  createdAt: Date;
  updatedAt: Date;
}
